---
- name: Playbook to configure my personal workstation
  hosts: localhost
  become: yes
  roles:
    - name: Non-specific tasks
      role: other
    - name: Application specific tasks
      role: apps
    - name: Development specific tasks
      role: development
    - name: Gaming specific tasks
      role: gaming