---
- name: Clone Spotify repo from AUR
  git:  
    repo: https://aur.archlinux.org/spotify.git
    dest: /tmp/spotify

- name: Import GPG key
  shell:
    cmd: curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | gpg --import -

- name: Install Spotify
  shell:
    cmd: makepkg -sic --noconfirm
    chdir: /tmp/spotify
  ignore_errors: true